import os
import time
os.system("apk add python2")
time.sleep(2)
os.system("apk add php")
time.sleep(1)
os.system("apk add ruby")
time.sleep(1)
os.system("apk add figlet")
time.sleep(1)
os.system("apk add bash")
os.system("apk add update py-pip")
os.system("apk add py-pip")
os.system("pip install requests")
os.system("pip2 install requests")
os.system("pip install mechanize")
os.system("pip2 install mechanize")
os.system("pip install telethone")
os.system("pip2 install telethone")
